name: CI/CD Workflow 

on:
  push:
    branches: [ main ] 

jobs:
  deploy: 
    name: DeployToProduction 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: tausif40/PatelAutomotive-API # Replace with your repo name
          ref: main 
          token: ${{ secrets.TOKEN }} # Use your secret

      - name: Connect to VPS using SSH
        uses: webfactory/ssh-agent@v0.5.4 
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }} 

      - name: Check Existing Directory and Delete
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'if [[ -d /var/www/PatelAutomotive-API ]]; then rm -rf /var/www/PatelAutomotive-API; fi' 

      - name: Clone Repository (using PAT)
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'git clone https://tausif40:${{ secrets.TOKEN }}@github.com/tausif40/PatelAutomotive-API.git /var/www/PatelAutomotive-API'

      - name: Install Dependencies
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /var/www/PatelAutomotive-API && npm install'


      - name: Restart Node.js Process
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /var/www/PatelAutomotive-API && PATH=$PATH:/usr/local/bin pm2 restart app.js' 

      - name: Restart Apache2
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo service apache2 restart' 